export const types = {
    CHANGE_TITLE: 'CHANGE_TITLE',
    CHANGE_DATA: 'CHANGE_DATA',
    CLEAR_DATA: 'CLEAR_DATA',
    ADD_USER: 'ADD_USER',


    CREATE_NUMBER: 'CREATE_NUMBER',
    ADD_NUMBER: 'ADD_NUMBER',
    CLEAR_INPUT_NUMBER: 'CLEAR_INPUT_NUMBER'
}